workflows:
  ios-build:
    name: iOS Build Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest  # Ensure this matches your available Xcode version
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign  # You can remove --no-codesign if you want code signing
    artifacts:
      - build/ios/ipa/*.ipa  # This will save the generated IPA file
    publishing:
      email:
        recipients:
          - m@gmail.com  # Replace with your email
      scripts:
        - echo 'Post-publish script'
