workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 13.4  # Use a supported Xcode version
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod repo update      # Update the CocoaPods repo
          pod install          # Install the necessary CocoaPods dependencies
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign -v   # Add verbose for more logs
    artifacts:
      - build/ios/ipa/*.ipa  # Collect the IPA file as an artifact for download
