workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 14.0.0  # Or a compatible Xcode version
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod repo update  # Update CocoaPods repo
          pod install      # Install necessary pods
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign -v  # Add verbose flag for debugging
    artifacts:
      - build/ios/ipa/*.ipa
