workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      variables:
        APPLE_TEAM_ID: "elawady"          # Replace with your Apple Team ID
        BUNDLE_ID: "com.example.finalmarcapp"     # Replace with your app's bundle ID
        CODE_SIGN_STYLE: "automatic"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
